/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import classes.Combo;
import classes.ConexaoPostgresql;
import classes.Funcoes;
import classes.TextDocument;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Tecsuport
 */
public class CadastroSerieMotorola extends javax.swing.JInternalFrame {

    private ConexaoPostgresql Conexao;
    private Funcoes Fun;    
    private TextDocument TD;
    
    /**
     * Creates new form CadastroSerieMotorola
     */
    public CadastroSerieMotorola() {
        initComponents();
        
    }
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroSerieMotorola().setVisible(true);
            }
        });
    }

    public void centralizar(JDesktopPane dp) {
        Dimension ds = dp.getSize();
        Dimension dw = this.getSize();
        this.setLocation((ds.width - dw.width) / 2, (ds.height - dw.height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbCodigo = new javax.swing.JLabel();
        jlbProduto = new javax.swing.JLabel();
        jlbFabricante = new javax.swing.JLabel();
        jlbSerie = new javax.swing.JLabel();
        chkBaixaRadio = new javax.swing.JCheckBox();
        jtfCodigo = new javax.swing.JFormattedTextField();
        jtfCodigoProduto = new javax.swing.JFormattedTextField();
        jtfNomeProduto = new javax.swing.JFormattedTextField();
        jtfCodigoFabricante = new javax.swing.JFormattedTextField();
        jtfNomeFabricante = new javax.swing.JFormattedTextField();
        jtfSerie = new javax.swing.JFormattedTextField();
        jlbDanfeFornecedor = new javax.swing.JLabel();
        jtfDanfeFornecedor = new javax.swing.JFormattedTextField();
        jlbDataDanfe = new javax.swing.JLabel();
        jdcDataDanfe = new com.toedter.calendar.JDateChooser();
        jbtNovo = new javax.swing.JButton();
        jbtSalvar = new javax.swing.JButton();
        jbtExcluir = new javax.swing.JButton();
        jbtPesquisar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastro de Série dos Rádio Motorola");
        setToolTipText("");

        jlbCodigo.setText("Código");

        jlbProduto.setText("Produto (F12)");

        jlbFabricante.setText("Fabricante (F12)");

        jlbSerie.setText("Série");

        chkBaixaRadio.setText("Rádio já retirado do estoque");

        jtfCodigo.setEnabled(false);

        jtfCodigoProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCodigoProdutoFocusLost(evt);
            }
        });
        jtfCodigoProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCodigoProdutoKeyPressed(evt);
            }
        });

        jtfCodigoFabricante.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCodigoFabricanteFocusLost(evt);
            }
        });
        jtfCodigoFabricante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCodigoFabricanteKeyPressed(evt);
            }
        });

        jlbDanfeFornecedor.setText("DANFE do Fornecedor");

        jlbDataDanfe.setText("Data da DANFE");

        jbtNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Novo.png"))); // NOI18N
        jbtNovo.setText("Novo");
        jbtNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNovoActionPerformed(evt);
            }
        });

        jbtSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Salvar.png"))); // NOI18N
        jbtSalvar.setText("Salvar");
        jbtSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalvarActionPerformed(evt);
            }
        });

        jbtExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Excluir.png"))); // NOI18N
        jbtExcluir.setText("Excluir");
        jbtExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExcluirActionPerformed(evt);
            }
        });

        jbtPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Pesquisa.png"))); // NOI18N
        jbtPesquisar.setText("Pesquisar");
        jbtPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbFabricante)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbCodigo)
                        .addGap(48, 48, 48)
                        .addComponent(jlbProduto))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfNomeProduto))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfCodigoFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfNomeFabricante, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbSerie))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlbDanfeFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfDanfeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbDataDanfe)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jdcDataDanfe, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkBaixaRadio))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jbtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jbtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jbtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCodigo)
                    .addComponent(jlbProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbFabricante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCodigoFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNomeFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbSerie)
                    .addComponent(jlbDanfeFornecedor)
                    .addComponent(jlbDataDanfe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfDanfeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jdcDataDanfe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkBaixaRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNovoActionPerformed

        Limpar();

        jtfCodigoProduto.requestFocus();
        
    }//GEN-LAST:event_jbtNovoActionPerformed

    private void jbtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalvarActionPerformed

        if (jtfCodigo.getText().equals("")){
//            Fun = new Funcoes();
//            jtfCodigo.setText(Fun.Proximo("codigo", "t_serie", ""));
            jtfCodigo.setText("0");
        }

        Conexao = new ConexaoPostgresql();
        Conexao.Conectar();
        Conexao.setSQL("select * from t_serie where codigo = " + jtfCodigo.getText() + " and exclusao = 0 ");
        ResultSet RS = Conexao.Consultar();

        String myDate = null;

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        myDate = sdf.format(jdcDataDanfe.getDate());
        
        char Baixa;
        
        if (chkBaixaRadio.isSelected()) {
            Baixa = '1';
        } else {
            Baixa = '0';
        }

        try {
            if(RS.next()){
                String SQL;

                SQL = "update t_serie set produto_cod = " + jtfCodigoProduto.getText() + ", ";
                SQL = SQL + "fabricante_cod = " + jtfCodigoFabricante.getText() + ", ";
                SQL = SQL + "serie = '" + jtfSerie.getText() + "', ";
                SQL = SQL + "danfe = '" + jtfDanfeFornecedor.getText() + "', ";
                SQL = SQL + "data_danfe = '" + myDate + "', ";
                SQL = SQL + "baixa = " + Baixa + " ";
                SQL = SQL + "where codigo = " + jtfCodigo.getText() + " ";

                Conexao.setSQL(SQL);
                Conexao.Executar();
            } else {
                String SQL;

                SQL = "insert into t_serie (produto_cod, fabricante_cod, serie, danfe, data_danfe, baixa, exclusao) ";
                SQL = SQL + "values (" + jtfCodigoProduto.getText() + ", " + jtfCodigoFabricante.getText() + ", '";
                SQL = SQL + jtfSerie.getText() + "', '" + jtfDanfeFornecedor.getText() + "', '" + myDate + "', " + Baixa + ", 0) ";
                

                Conexao.setSQL(SQL);
                Conexao.Executar();
            }

        } catch (Exception Erro) {
            JOptionPane.showMessageDialog(null, "Erro na validação: " + Erro);
        }

        Conexao.Desconectar();

        Limpar();

        jtfCodigoProduto.requestFocus();

    }//GEN-LAST:event_jbtSalvarActionPerformed

    private void jbtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExcluirActionPerformed

        if (!(jtfCodigo.getText().trim().equals(""))) {

            Object[] botoes = { "Sim", "Não" };

            int resposta;

            resposta = JOptionPane.showOptionDialog(null, "Você deseja realmente excluir este registro?", "Confirma exclusão", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE, null, botoes, botoes[0]);

            if(resposta == JOptionPane.YES_OPTION){

                String SQL = "update t_serie set exclusao = 1 where codigo = " + jtfCodigo.getText() + " ";

                Conexao = new ConexaoPostgresql();
                Conexao.Conectar();
                Conexao.setSQL(SQL);
                Conexao.Executar();
                Conexao.Desconectar();

                Limpar();

            }

            jtfCodigoProduto.requestFocus();

        }

    }//GEN-LAST:event_jbtExcluirActionPerformed

    private void jbtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPesquisarActionPerformed

        PesquisaSerie A = new PesquisaSerie();
        A.setVisible(true);
        JDesktopPane JDP = this.getDesktopPane();
        JDP.add(A);
        A.centralizar(JDP);
        try{
            A.setSelected(true);
            A.SetCidade(this);
            A.Validador("Serie");
        }catch (Exception E){
            JOptionPane.showMessageDialog(null, "Erro: " + E);
        }
        A.setVisible(true);

    }//GEN-LAST:event_jbtPesquisarActionPerformed

    private void jtfCodigoProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodigoProdutoKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
           
            jtfNomeProduto.setText(NomeProduto(Integer.parseInt(jtfCodigoProduto.getText())));
            
            jtfCodigoFabricante.requestFocus();

        }
        
        if(evt.getKeyCode() == KeyEvent.VK_F12){
        
            SubPesquisaProduto A = new SubPesquisaProduto();
            A.setVisible(true);
            JDesktopPane JDP = this.getDesktopPane();
            JDP.add(A);
            A.centralizar(JDP);
            try{
                A.setSelected(true);
                A.SetSubProduto(this);
                A.Validador("Produto");
            }catch (Exception E){
                JOptionPane.showMessageDialog(null, "Erro: " + E);
            }
            A.setVisible(true);
            
        }
        
    }//GEN-LAST:event_jtfCodigoProdutoKeyPressed

    private void jtfCodigoProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCodigoProdutoFocusLost
        
        if (!(jtfCodigoProduto.getText().trim().equals(""))) {
        
            jtfNomeProduto.setText(NomeProduto(Integer.parseInt(jtfCodigoProduto.getText())));
            
            jtfCodigoFabricante.requestFocus();
        
        }
        
    }//GEN-LAST:event_jtfCodigoProdutoFocusLost

    private void jtfCodigoFabricanteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodigoFabricanteKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
           
            jtfNomeFabricante.setText(NomeFabricante(Integer.parseInt(jtfCodigoFabricante.getText())));
            
            jtfSerie.requestFocus();

        }
        
        if(evt.getKeyCode() == KeyEvent.VK_F12){
        
            SubPesquisaPessoa A = new SubPesquisaPessoa();
            A.setVisible(true);
            JDesktopPane JDP = this.getDesktopPane();
            JDP.add(A);
            A.centralizar(JDP);
            try{
                A.setSelected(true);
                A.SetSubFabricante(this);
                A.Validador("Fabricante");
            }catch (Exception E){
                JOptionPane.showMessageDialog(null, "Erro: " + E);
            }
            A.setVisible(true);
            
        }
        
    }//GEN-LAST:event_jtfCodigoFabricanteKeyPressed

    private void jtfCodigoFabricanteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCodigoFabricanteFocusLost
        
        if (!(jtfCodigoFabricante.getText().trim().equals(""))) {
        
            jtfNomeFabricante.setText(NomeFabricante(Integer.parseInt(jtfCodigoFabricante.getText())));
            
            jtfSerie.requestFocus();
        
        }
        
    }//GEN-LAST:event_jtfCodigoFabricanteFocusLost

    private void Limpar () {
        
        jtfCodigo.setText("");
        jtfCodigoProduto.setText("");
        jtfNomeProduto.setText("");
        jtfCodigoFabricante.setText("");
        jtfNomeFabricante.setText("");
        jtfSerie.setText("");
        jtfDanfeFornecedor.setText("");
        jdcDataDanfe.setDate(new java.util.Date());        
        chkBaixaRadio.setSelected(false);
        
    }
    
    public void CarregarDados(String Codigo){
        
        String SQL;
        
        SQL = "select ts.codigo, ts.produto_cod, (tpr.nome) as nomeproduto, ts.fabricante_cod, (tp.nome) as nomefabricante, ts.serie, ";
        SQL = SQL + "ts.danfe, to_char(ts.data_danfe,'DD/MM/YYYY') as datadanfe, ts.baixa ";
        SQL = SQL + "from t_serie ts ";
        SQL = SQL + "inner join t_produto tpr on tpr.codigo = ts.produto_cod ";
        SQL = SQL + "inner join t_pessoa tp on tp.codigo = ts.fabricante_cod ";
        SQL = SQL + "where ts.codigo = " + Codigo + " ";
        SQL = SQL + "and ts.exclusao = 0 ";
        
        Conexao = new ConexaoPostgresql();
        Conexao.Conectar() ;
        Conexao.setSQL(SQL);
        
        System.out.println(SQL);

        ResultSet RS = Conexao.Consultar();
        
        try{
            if (RS.next()){
                jtfCodigo.setText(RS.getString("codigo"));
                jtfCodigoProduto.setText(RS.getString("produto_cod"));
                jtfNomeProduto.setText(RS.getString("nomeproduto"));
                jtfCodigoFabricante.setText(RS.getString("fabricante_cod"));
                jtfNomeFabricante.setText(RS.getString("nomefabricante"));
                jtfSerie.setText(RS.getString("serie"));
                jtfDanfeFornecedor.setText(RS.getString("danfe"));
                jdcDataDanfe.setDate(RS.getDate("datadanfe"));

                if (RS.getString("baixa").equals("1")) {
                        chkBaixaRadio.setSelected(true);
                }
            }
        }catch (Exception Erro){
            JOptionPane.showMessageDialog(null, "Erro na validação: " + Erro);
        }
        
        Conexao.Desconectar();
        
    }

    public String NomeProduto (int CodigoProduto){
    
        String Produto = null;
        
        Fun = new Funcoes();
        Produto = Fun.NomeProduto(CodigoProduto);
        
        return Produto;        
    
    }
    
    public void NomeProdutoViaF12 (int CodigoProduto){
        
        jtfCodigoProduto.setText(String.valueOf(CodigoProduto));
        jtfNomeProduto.setText(NomeProduto(CodigoProduto));
        
    }
    
    public String NomeFabricante (int CodigoFabricante){
    
        String Fabricante = null;
        
        Fun = new Funcoes();
        Fabricante = Fun.NomePessoa(CodigoFabricante);
        
        return Fabricante;        
    
    }
    
    public void NomeFabricanteViaF12 (int CodigoFabricante){
        
        jtfCodigoFabricante.setText(String.valueOf(CodigoFabricante));
        jtfNomeFabricante.setText(NomeFabricante(CodigoFabricante));
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkBaixaRadio;
    private javax.swing.JButton jbtExcluir;
    private javax.swing.JButton jbtNovo;
    private javax.swing.JButton jbtPesquisar;
    private javax.swing.JButton jbtSalvar;
    private com.toedter.calendar.JDateChooser jdcDataDanfe;
    private javax.swing.JLabel jlbCodigo;
    private javax.swing.JLabel jlbDanfeFornecedor;
    private javax.swing.JLabel jlbDataDanfe;
    private javax.swing.JLabel jlbFabricante;
    private javax.swing.JLabel jlbProduto;
    private javax.swing.JLabel jlbSerie;
    private javax.swing.JFormattedTextField jtfCodigo;
    private javax.swing.JFormattedTextField jtfCodigoFabricante;
    private javax.swing.JFormattedTextField jtfCodigoProduto;
    private javax.swing.JFormattedTextField jtfDanfeFornecedor;
    private javax.swing.JFormattedTextField jtfNomeFabricante;
    private javax.swing.JFormattedTextField jtfNomeProduto;
    private javax.swing.JFormattedTextField jtfSerie;
    // End of variables declaration//GEN-END:variables
}
